version: '2'
services:
    smarti-app:
        image: smarti
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://smarti-mysql:3306/smarti?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://smarti-elasticsearch:9200
        ports:
            - 8080:8080
    smarti-mysql:
        extends:
            file: mysql.yml
            service: smarti-mysql
    smarti-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: smarti-elasticsearch
